### PR TITLE
Add options accessors

### PR DESCRIPTION
**Pull request by krampstudio**
Related to https://oat-sa.atlassian.net/browse/TRN-720

 - Add accessors for the item runner's `options`. The provider can implement the setter optionally.  This will be useful to update the settings while the item runner is running.

 Requires: 
 - [x] https://github.com/oat-sa/tao-item-runner-fe/pull/38

Companion PRs:
 - [ ] https://github.com/oat-sa/tao-item-runner-qtinui-fe/pull/389
 - [ ] https://github.com/oat-sa/tao-test-runner-qtinui-fe/pull/273

How to test:
 - [ ] run the unit tests
 - [ ] check with companion PRs

### CODE REVIEW

**Review by oatymart — APPROVED** [review]
It looks ok to me. From this view the `options` is an all-purpose property, I'm looking forward to seeing in NUI a high-level view of which types of data will exist in which stores and when they will be submitted via this API.

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Documentation is updated according to changes (if applicable)

**Review by olga-kulish — APPROVED** [review]
Looks good. Test runs well.
As I understand from companion PRs, it's not used anywhere now (since we recreate item-runner when closing settings overview).

**Comment by krampstudio** [comment]
> Looks good. Test runs well.
> As I understand from companion PRs, it's not used anywhere now (since we recreate item-runner when closing settings overview).

This is my original implementation:
https://github.com/oat-sa/tao-test-runner-qtinui-fe/pull/273/commits/0e1ab7c6abe4528206667b9d12349f917254380c#diff-88943aa5fbf5f61e5a574aa16bef64fbe54d93bf33cdbbf63e09b46575e075acR405-R411
where I subscribe to the store to update the item runner's options.
I can keep it in case the settings store is updated somewhere else.

**Comment by olga-kulish** [comment]
> 
> 
> > Looks good. Test runs well.
> > As I understand from companion PRs, it's not used anywhere now (since we recreate item-runner when closing settings overview).
> 
> This is my original implementation:
> [oat-sa/tao-test-runner-qtinui-fe@0e1ab7c#diff-88943aa5fbf5f61e5a574aa16bef64fbe54d93bf33cdbbf63e09b46575e075acR405-R411](https://github.com/oat-sa/tao-test-runner-qtinui-fe/commit/0e1ab7c6abe4528206667b9d12349f917254380c#diff-88943aa5fbf5f61e5a574aa16bef64fbe54d93bf33cdbbf63e09b46575e075acR405-R411)
> where I subscribe to the store to update the item runner's options.
> I can keep it in case the settings store is updated somewhere else.

Ok, thank you for explanation. I think it's better to keep it like now (pass settings on init), since it's simpler. 
This should still be useful in the future.

**Comment by olga-kulish** [comment]
> Ok, thank you for explanation. I think it's better to keep it like now (pass settings on init), since it's simpler.
> This should still be very in the future.

I see you've updated it. Still I prefer simpler version, but let's keep it, it's fine.

**Pull request merged**
